http:
        image: nginx
        ports:
                - "80:80"
        volumes:
                - ./http/nginx_conf.d:/etc/nginx/conf.d
                - ./http/static:/var/www/
        links:
                - wsgi
                
wsgi:
        build: wsgi
        volumes:
                - ./wsgi/init:/usr/src/at-build/init
                - ./django-project:/usr/src/app
                - ./http/static:/var/www/
        links:
                - redis
                - db
                
db:
        image: postgres
        volumes:
                - ./db/data:/var/lib/postgresql/data
        environment:
                POSTGRES_PASSWORD: admin
        ports:
                - "5432:5432"

redis:
        image: redis
# Uncomment if need of persistence
#        volumes:
#                - ./redis/data:/data
        ports:
                - "6379:6379"
