db:
        image: postgres
        volumes:
                - ./db/data:/var/lib/postgresql/data
        environment:
                POSTGRES_PASSWORD: admin
        ports:
                - "5432:5432"

redis:
        image: redis
        ports:
                - "6379:6379"
wsgi:
        build: wsgi
        ports:
                - "8080:8080" # Use for the dev server
        volumes:
                - ./wsgi/log:/var/log/cyder/
                - ./django-project:/usr/src/app
                - ./http/static:/var/www/ # Where static files are collected to be served
        links:
                - redis
                - db
http:
        image: nginx
        ports:
                - "80:80"
                - "443:443"
        volumes:
                - ./http/nginx_conf.d:/etc/nginx/conf.d
                - ./http/ssl:/etc/nginx/ssl
                - ./http/static:/var/www/ # Where static files are collected to be served
        links:
                - wsgi
                
# dummy_worker:
#         build: dummy_worker
#         links:
#                 - redis